version: '3'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
  datascience:
    build: ./datascience
    ports:
      - "8888:8888"
    volumes:
      - ./datascience/notebooks:/app/notebooks
    links:
      - cassandra
volumes:
  cassandra_data:

